//************************************************************************************
//**  
//**  File name:     D:\MCU_projects\Flowcode\Pedestrian_traffic_light_control.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Sunday, December 09, 2018 11:42:21
//**  Licence:       Professional
//**  Registered to: uzo_ochogu
//**  Licence key:   7CJZMH
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877A
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_1
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 19660800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f72
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f72);
#endif

//Internal functions
#include "C:\Program Files\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_safety();
void FCM_vehicles_moving();
void FCM_pedestrian_crossing();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_COUNTER = (0x0);
MX_BOOL FCV_SWITCH2_STATE = (0);
MX_BOOL FCV_SWITCH_STATE = (0);




//LED(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_3__LED_PORT		portb
#define LED_3__LED_TRIS		trisb
#define LED_3__LED_PIN		0
#define LED_3__LED_POLE		1




//LED(0): //Macro function declarations

void FCD_LED0_LEDOn();
void FCD_LED0_LEDOff();


//LED(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_4__LED_PORT		portb
#define LED_4__LED_TRIS		trisb
#define LED_4__LED_PIN		1
#define LED_4__LED_POLE		1




//LED(1): //Macro function declarations

void FCD_LED1_LEDOn();
void FCD_LED1_LEDOff();


//LED(2): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_5__LED_PORT		portb
#define LED_5__LED_TRIS		trisb
#define LED_5__LED_PIN		2
#define LED_5__LED_POLE		1




//LED(2): //Macro function declarations

void FCD_LED2_LEDOn();
void FCD_LED2_LEDOff();


//LED(3): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_6__LED_PORT		portb
#define LED_6__LED_TRIS		trisb
#define LED_6__LED_PIN		3
#define LED_6__LED_POLE		1




//LED(3): //Macro function declarations

void FCD_LED3_LEDOn();
void FCD_LED3_LEDOff();


//LED(4): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_7__LED_PORT		portb
#define LED_7__LED_TRIS		trisb
#define LED_7__LED_PIN		4
#define LED_7__LED_POLE		1




//LED(4): //Macro function declarations

void FCD_LED4_LEDOn();
void FCD_LED4_LEDOff();


//LED(5): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_8__LED_PORT		portb
#define LED_8__LED_TRIS		trisb
#define LED_8__LED_PIN		5
#define LED_8__LED_POLE		1




//LED(5): //Macro function declarations

void FCD_LED5_LEDOn();
void FCD_LED5_LEDOff();


//LED(6): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_9__LED_PORT		portb
#define LED_9__LED_TRIS		trisb
#define LED_9__LED_PIN		6
#define LED_9__LED_POLE		1




//LED(6): //Macro function declarations

void FCD_LED6_LEDOn();
void FCD_LED6_LEDOff();


//LED(7): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_10__LED_PORT		portb
#define LED_10__LED_TRIS		trisb
#define LED_10__LED_PIN		7
#define LED_10__LED_POLE		1




//LED(7): //Macro function declarations

void FCD_LED7_LEDOn();
void FCD_LED7_LEDOff();


//LED(8): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_11__LED_PORT		portc
#define LED_11__LED_TRIS		trisc
#define LED_11__LED_PIN		0
#define LED_11__LED_POLE		1




//LED(8): //Macro function declarations

void FCD_LED8_LEDOn();
void FCD_LED8_LEDOff();


//LED(9): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_12__LED_PORT		portc
#define LED_12__LED_TRIS		trisc
#define LED_12__LED_PIN		1
#define LED_12__LED_POLE		1




//LED(9): //Macro function declarations

void FCD_LED9_LEDOn();
void FCD_LED9_LEDOff();


//led7seg(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Segment Port letter
c = Common Port letter
d = Segment Pin 0
e = Segment Pin 1
f = Segment Pin 2
g = Segment Pin 3
h = Segment Pin 4
i = Segment Pin 5
j = Segment Pin 6
k = Segment Pin 7
l = Common Pin
m = Display Type 0=Common Cathode, 1=Common Anode
******************************/

#define SEVENSEG1_19_SEG_PORT		portd
#define SEVENSEG1_19_SEG_TRIS		trisd
#define SEVENSEG1_19_COM_PORT		portc
#define SEVENSEG1_19_COM_TRIS		trisc
#define SEVENSEG1_19_SEG_PIN0		0
#define SEVENSEG1_19_SEG_PIN1		1
#define SEVENSEG1_19_SEG_PIN2		2
#define SEVENSEG1_19_SEG_PIN3		3
#define SEVENSEG1_19_SEG_PIN4		4
#define SEVENSEG1_19_SEG_PIN5		5
#define SEVENSEG1_19_SEG_PIN6		6
#define SEVENSEG1_19_SEG_PIN7		7
#define SEVENSEG1_19_COM_PIN		2
#define SEVENSEG1_19_COM_TYPE		1

#ifndef SEVENSEG1_19_ARRAY
 #define SEVENSEG1_19_ARRAY
 ROMARRAY_S SEVENSEG1_19_SegmentArray ROMARRAY_E = {192, 249, 164, 176, 153, 146, 130, 248, 128, 152};		//Create ROM pattern array for the display
#endif




//led7seg(0): //Macro function declarations

void FCD_led7seg0_ShowDigit(MX_UINT8 Value, MX_UINT8 DecimalPoint);
void FCD_led7seg0_ClearDigit();



//LED(0): //Macro implementations


void FCD_LED0_LEDOn()
{
	
		#if( LED_3__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#endif

}

void FCD_LED0_LEDOff()
{
	
		#if( LED_3__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_3__LED_PORT	, LED_3__LED_TRIS , LED_3__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#endif

}



//LED(1): //Macro implementations


void FCD_LED1_LEDOn()
{
	
		#if( LED_4__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_4__LED_PORT , LED_4__LED_TRIS , LED_4__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_4__LED_PORT , LED_4__LED_TRIS , LED_4__LED_PIN );
		#endif

}

void FCD_LED1_LEDOff()
{
	
		#if( LED_4__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_4__LED_PORT	, LED_4__LED_TRIS , LED_4__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_4__LED_PORT , LED_4__LED_TRIS , LED_4__LED_PIN );
		#endif

}



//LED(2): //Macro implementations


void FCD_LED2_LEDOn()
{
	
		#if( LED_5__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_5__LED_PORT , LED_5__LED_TRIS , LED_5__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_5__LED_PORT , LED_5__LED_TRIS , LED_5__LED_PIN );
		#endif

}

void FCD_LED2_LEDOff()
{
	
		#if( LED_5__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_5__LED_PORT	, LED_5__LED_TRIS , LED_5__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_5__LED_PORT , LED_5__LED_TRIS , LED_5__LED_PIN );
		#endif

}



//LED(3): //Macro implementations


void FCD_LED3_LEDOn()
{
	
		#if( LED_6__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_6__LED_PORT , LED_6__LED_TRIS , LED_6__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_6__LED_PORT , LED_6__LED_TRIS , LED_6__LED_PIN );
		#endif

}

void FCD_LED3_LEDOff()
{
	
		#if( LED_6__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_6__LED_PORT	, LED_6__LED_TRIS , LED_6__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_6__LED_PORT , LED_6__LED_TRIS , LED_6__LED_PIN );
		#endif

}



//LED(4): //Macro implementations


void FCD_LED4_LEDOn()
{
	
		#if( LED_7__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_7__LED_PORT , LED_7__LED_TRIS , LED_7__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_7__LED_PORT , LED_7__LED_TRIS , LED_7__LED_PIN );
		#endif

}

void FCD_LED4_LEDOff()
{
	
		#if( LED_7__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_7__LED_PORT	, LED_7__LED_TRIS , LED_7__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_7__LED_PORT , LED_7__LED_TRIS , LED_7__LED_PIN );
		#endif

}



//LED(5): //Macro implementations


void FCD_LED5_LEDOn()
{
	
		#if( LED_8__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_8__LED_PORT , LED_8__LED_TRIS , LED_8__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_8__LED_PORT , LED_8__LED_TRIS , LED_8__LED_PIN );
		#endif

}

void FCD_LED5_LEDOff()
{
	
		#if( LED_8__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_8__LED_PORT	, LED_8__LED_TRIS , LED_8__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_8__LED_PORT , LED_8__LED_TRIS , LED_8__LED_PIN );
		#endif

}



//LED(6): //Macro implementations


void FCD_LED6_LEDOn()
{
	
		#if( LED_9__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_9__LED_PORT , LED_9__LED_TRIS , LED_9__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_9__LED_PORT , LED_9__LED_TRIS , LED_9__LED_PIN );
		#endif

}

void FCD_LED6_LEDOff()
{
	
		#if( LED_9__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_9__LED_PORT	, LED_9__LED_TRIS , LED_9__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_9__LED_PORT , LED_9__LED_TRIS , LED_9__LED_PIN );
		#endif

}



//LED(7): //Macro implementations


void FCD_LED7_LEDOn()
{
	
		#if( LED_10__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_10__LED_PORT , LED_10__LED_TRIS , LED_10__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_10__LED_PORT , LED_10__LED_TRIS , LED_10__LED_PIN );
		#endif

}

void FCD_LED7_LEDOff()
{
	
		#if( LED_10__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_10__LED_PORT	, LED_10__LED_TRIS , LED_10__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_10__LED_PORT , LED_10__LED_TRIS , LED_10__LED_PIN );
		#endif

}



//LED(8): //Macro implementations


void FCD_LED8_LEDOn()
{
	
		#if( LED_11__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_11__LED_PORT , LED_11__LED_TRIS , LED_11__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_11__LED_PORT , LED_11__LED_TRIS , LED_11__LED_PIN );
		#endif

}

void FCD_LED8_LEDOff()
{
	
		#if( LED_11__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_11__LED_PORT	, LED_11__LED_TRIS , LED_11__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_11__LED_PORT , LED_11__LED_TRIS , LED_11__LED_PIN );
		#endif

}



//LED(9): //Macro implementations


void FCD_LED9_LEDOn()
{
	
		#if( LED_12__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_12__LED_PORT , LED_12__LED_TRIS , LED_12__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_12__LED_PORT , LED_12__LED_TRIS , LED_12__LED_PIN );
		#endif

}

void FCD_LED9_LEDOff()
{
	
		#if( LED_12__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_12__LED_PORT	, LED_12__LED_TRIS , LED_12__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_12__LED_PORT , LED_12__LED_TRIS , LED_12__LED_PIN );
		#endif

}



//led7seg(0): //Macro implementations


void FCD_led7seg0_ShowDigit(MX_UINT8 Value, MX_UINT8 DecimalPoint)
{
	
		MX_UINT8 cSegmentValue = SEVENSEG1_19_SegmentArray[Value % 10];

		if (DecimalPoint)
			cSegmentValue = cSegmentValue & 0x7F;			//Clear decimal point bit

		//display the digit
	    #if (SEVENSEG1_19_COM_TYPE == 1)						//Common Anode - Low = on, High = off

			if (cSegmentValue & 0x01)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN0);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN0);
			}

			if (cSegmentValue & 0x02)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN1);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN1);
			}

			if (cSegmentValue & 0x04)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN2);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN2);
			}

			if (cSegmentValue & 0x08)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN3);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN3);
			}

			if (cSegmentValue & 0x10)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN4);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN4);
			}

			if (cSegmentValue & 0x20)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN5);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN5);
			}

			if (cSegmentValue & 0x40)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN6);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN6);
			}

			if (cSegmentValue & 0x80)
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN7);
			}
			else
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN7);
			}

			FC_CAL_Bit_High_DDR(SEVENSEG1_19_COM_PORT, SEVENSEG1_19_COM_TRIS, SEVENSEG1_19_COM_PIN);

		#else												//Common Cathode - Low = off, High = on

			if (cSegmentValue & 0x01)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN0);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN0);
			}

			if (cSegmentValue & 0x02)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN1);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN1);
			}

			if (cSegmentValue & 0x04)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN2);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN2);
			}

			if (cSegmentValue & 0x08)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN3);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN3);
			}

			if (cSegmentValue & 0x10)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN4);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN4);
			}

			if (cSegmentValue & 0x20)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN5);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN5);
			}

			if (cSegmentValue & 0x40)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN6);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN6);
			}

			if (cSegmentValue & 0x80)
			{
				FC_CAL_Bit_Low_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN7);
			}
			else
			{
				FC_CAL_Bit_High_DDR(SEVENSEG1_19_SEG_PORT, SEVENSEG1_19_SEG_TRIS, SEVENSEG1_19_SEG_PIN7);
			}

			FC_CAL_Bit_Low_DDR(SEVENSEG1_19_COM_PORT, SEVENSEG1_19_COM_TRIS, SEVENSEG1_19_COM_PIN);

		#endif

}

void FCD_led7seg0_ClearDigit()
{
	
		#if (SEVENSEG1_19_COM_TYPE == 1)
			FC_CAL_Bit_Low_DDR(SEVENSEG1_19_COM_PORT, SEVENSEG1_19_COM_TRIS, SEVENSEG1_19_COM_PIN);		//common anode
		#else
			FC_CAL_Bit_High_DDR(SEVENSEG1_19_COM_PORT, SEVENSEG1_19_COM_TRIS, SEVENSEG1_19_COM_PIN);		//common cathode
		#endif

}

#include "C:\Program Files\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_safety()
{

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED0_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED1_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED2_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED3_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED4_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED5_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED6_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED7_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED8_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED9_LEDOff();

}


void FCM_vehicles_moving()
{

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED0_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED1_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED2_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED3_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED4_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED5_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED6_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED7_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED8_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED9_LEDOn();

}


void FCM_pedestrian_crossing()
{

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED0_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED1_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED2_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED3_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED4_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED5_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED6_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED7_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED8_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED9_LEDOff();

}



void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Macro
		//Call Macro: 
		//No code generated because there is no macro name

		//Call Macro
		//Call Macro: vehicles_moving()
		FCM_vehicles_moving();

		//Input
		//Input: A0 -> switch_state
		trisa = trisa | 0x01;
		FCV_SWITCH_STATE = ((porta & 0x01) == 0x01);

		//Input
		//Input: A1 -> switch2_state
		trisa = trisa | 0x02;
		FCV_SWITCH2_STATE = ((porta & 0x02) == 0x02);

		//Call Component Macro
		//Call Component Macro: ClearDigit()
		FCD_led7seg0_ClearDigit();

		//Decision
		//Decision: switch_state = 1 || switch2_state = 1?
		if (FCV_SWITCH_STATE == 1 || FCV_SWITCH2_STATE == 1)
		{

			//Call Macro
			//Call Macro: safety()
			FCM_safety();

			//Delay
			//Delay: 5 s
			delay_s(5);

			//Call Macro
			//Call Macro: pedestrian_crossing()
			FCM_pedestrian_crossing();

			//Loop
			//Loop: While counter < 10
			while (FCV_COUNTER < 10)
			{

				//Call Component Macro
				//Call Component Macro: ShowDigit(counter, false)
				FCD_led7seg0_ShowDigit(FCV_COUNTER, FCV_FALSE);

				//Delay
				//Delay: 1 s
				delay_s(1);

				//
				//Calculation:
				//  counter = counter + 1
				FCV_COUNTER = FCV_COUNTER + 1;


			}

			//Call Component Macro
			//Call Component Macro: ClearDigit()
			FCD_led7seg0_ClearDigit();

			//Call Macro
			//Call Macro: safety()
			FCM_safety();

			//Delay
			//Delay: 5 s
			delay_s(5);

			//Call Macro
			//Call Macro: vehicles_moving()
			FCM_vehicles_moving();

		} else {

			//Call Macro
			//Call Macro: vehicles_moving()
			FCM_vehicles_moving();

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



